### ISSUE TITLE
fmt & clippy &  CI

### ISSUE THREAD

**Issue by cyphersnake** [LukasKalbertodt/confique#21]
As part of implementation #10, I fixed the clippy warnings and run fmt. If the maintainer has no fundamental objections to their comments or specific configuration files, then I would first make a separate PR with these edits by adding automatic checks by github actions

**Comment by LukasKalbertodt** [comment]
I sadly have to say no to the rustfmt suggestion. 

I just ran `cargo fmt` and unfortunately disagree with quite a few changes. I reverted the changes I disagree with and pushed the others as a new commit just now.
I do understand that a coherent style is more important and I'm all on board ditching minor preferences I have for the "greater good". And I tried again and again to use rustfmt in my projects, but it was unfortunately always too annoying. I guess my fundamental problem with it is that it has a very narrow definition of what's allowed. Its check mode is basically "format and check if there are any changes", which is bad IMO as there are often multiple ways one can write something. So yeah, no automatic rustfmt checking in this repo, sorry!

Regarding clippy: I also ran `cargo clippy` just now and fixed most warnings, but the `Default` warning I ignored because it's rather likely the manual impl is required in the near future anyway.

So... I'm sorry, but apart from those two commits I just pushed, I have to decline this.

Exciting to hear you are working on #10 though! Interested to see that.
