### ISSUE TITLE
`Hocon` support

### ISSUE THREAD

**Issue by samgj18** [LukasKalbertodt/confique#36]
First of all, great work. I was wondering if you had any plans to support Hocon in the future. I'd be more than glad to work on this feature myself in case you could use some help.

**Comment by LukasKalbertodt** [comment]
Hey, thanks! I'm generally not opposed to adding more useful configuration formats. Each is behind a Cargo feature anyway, so nothing will change for people not using them. But I do have some requirements:
- The biggest one: is there a `serde` library for it? `confique` does not implement any parsers itself and that's by design. Unless I'm missing something, there seems to be only [this crate](https://github.com/mockersf/hocon.rs) which is unmaintained, unfortunately. 
- Is the format widely used, especially by people using Rust? It's often hard to estimate this, but from some quick search it doesn't seem like it's used super widely by Rust people?
- Does it roughly fit into the existing `confique` structure? If I would have to redesign all of `confique`, that would be a no go. From just looking at it very briefly, it seems to be OK in this regard.

So overall not a great look for Hocon right now, especially the lack of maintained parser. Adding a format also adds maintenance burden on me. And if I have never heard of a format, that's not particularly great.

So unless you can show me a maintained parser crate for Hocon, my answer for now is sadly: "no". *However*, note that you can still use confique with non-built-in formats. For example, if u want to use that unmaintained library, you can simply deserialize into the `Partial` config. And the "configuration template" you can generate yourself from the [`META` description](https://docs.rs/confique/latest/confique/trait.Config.html#associatedconstant.META). That's exactly what the built-in "config template" functions do as well. It's not like the built-in functions have access to more internal information.

I hope that helps!

**Comment by samgj18** [comment]
Hey @LukasKalbertodt, that's understandable. I come from Scala where this is widely used. Was only hoping to find something familiar in that regard but truth be told the rust hocon library is unmaintained and there's no other at the moment. I believe that the best bet for me would be to deserialize the `Partial` configuration as you suggested. Appreciate the fast reply!
